# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=254)),
                ('body', models.TextField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My application.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Max length 50', max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('bussiness_type', models.CharField(help_text='Max length 20', max_length=20)),
                ('city', models.CharField(help_text='Max length 30', max_length=30)),
                ('domain', models.URLField(help_text='Max length 200')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_complaint', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Max length 50', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='categories',
            field=models.ManyToManyField(to='My application.Complaint_Category'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='My application.Company'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
