# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My application', '0004_company_my_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='my_field',
            new_name='validate',
        ),
    ]
